addons:
  sonarcloud:
    organization: "dahan5_retail-store-discounts" # the key of the org you chose at step #3
    token:
      secure: "7610f17f1ba3794ae5dfc61d815baa32bec8cf5b" # encrypted value of your token
script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
